[build]
  builder = "NIXPACKS"
  buildCommand = "npm install && npm run build:server"

[deploy]
<<<<<<< HEAD
  startCommand = "npm run start"
=======
  startCommand = "node dist/server/index.js"
>>>>>>> origin/main
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
